name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        include:
          - python-version: "3.7"
            toxenv: py37
          - python-version: "3.8"
            toxenv: py38
          - python-version: "3.9"
            toxenv: py39
          - python-version: "3.10"
            toxenv: py310
          - python-version: "3.11"
            toxenv: py311,syntax

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "tox"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: |
        tox
    - name: Self check
      run: |
        pip install .
        package-version-present `python setup.py --name` `python setup.py --version` -T -X
